README.rst
`java` is Java and `json` is JSON, except where JSON contains invalid `...` notation. I also fixed indentation which was incosistent between 3 and 4 spaces to 4 (four, quatre, vier) spaces. The one true indentation.
=> Code blocks and fixed whitespace

CHANGELOG.rst
Update the Changelog with the updated tickets for version 1.1.4
=> Add version 1.1.4 Changelog

payment/src/main/java/net/optile/payment/model/InstallmentsPlan.java, payment/src/main/java/net/optile/payment/model/Redirect.java
Update the Redirect and InstallmentsPlan model classes with new fields including the type field in Redirect.
=> PCX-210 Update model classes

example/build.gradle, example/src/androidTest/java/net/optile/payment/list/ListService.java
Fix the naming of system environment variables for automated UI tests.
=> PCX-231 fix automated UI tests

payment/src/main/java/net/optile/payment/network/ListConnection.java
Replace putIfAbsent with put since it is not supported until Android 24.
=> Update ListConnection putIfAbsent

README.rst
Update documentation explaining how to use the Android SDK together with a summary page.
=> Pcx 182 documentation update

payment/src/main/java/net/optile/payment/ui/theme/ProgressParameters.java, payment/src/test/java/net/optile/payment/ui/theme/ProgressParametersTest.java
Change background to white for send animation.
=> Change background color send animation

CHANGELOG.rst, README.rst
Update tickets completed in the CHANGELOG
Update packagecloud version number in the README
=> Update changelog and readme

payment/build.gradle
Check if the following properties exist when executing these tasks.
mavenUser
mavenPassword
packageCloudMavenPassword
=> Check if properties exist for uploading archives

example-basic/src/main/AndroidManifest.xml, example-demo/src/main/AndroidManifest.xml
Redirect activity must be set in order to make successful redirect payments.
=> PCX-428: Add redirect activities to examples

example-demo/src/androidTest/java/net/optile/example/demo/AbstractTest.java, example-demo/src/androidTest/java/net/optile/example/demo/UITestSuite.java
These changed did not seem to end up in the original PCX-780 PR.
=> PCX-780: Update and enable grouped tests

version.gradle
For example when major is increased then both minor and patch are reset to 0
=> PCX-849: Reset version name (minor, patch) to zero

payment/src/main/java/net/optile/payment/ui/list/PaymentList.java, payment/src/main/java/net/optile/payment/ui/list/PresetCardViewHolder.java, payment/src/main/res/color/payment_card_stroke_color.xml, payment/src/main/res/layout/list_item_presetcard.xml, payment/src/main/res/values/colors.xml, payment/src/main/res/values/dimens.xml, payment/src/main/res/values/styles.xml
1. Add minimum height of action button
2. Fix scrolling when expanding cards
3. Add stroke color for selected preset card
=> PCX-786: Acceptance test modifications

example-demo/src/main/java/net/optile/example/demo/summary/SummaryActivity.java, example-demo/src/main/java/net/optile/example/demo/summary/SummaryPresenter.java, example-demo/src/main/java/net/optile/example/demo/summary/SummaryView.java
SummaryActivity may crash when there was no payment network for the stored preset account.
=> PCX-1000: Fix crash in SummaryActivity

example-demo/src/main/java/net/optile/example/demo/checkout/CheckoutActivity.java, example-demo/src/main/java/net/optile/example/demo/checkout/CheckoutPresenter.java, example-demo/src/main/java/net/optile/example/demo/checkout/CheckoutView.java, example-demo/src/main/java/net/optile/example/demo/settings/SettingsActivity.java, example-demo/src/main/java/net/optile/example/demo/shared/BaseActivity.java, example-demo/src/main/java/net/optile/example/demo/summary/SummaryActivity.java, example-demo/src/main/java/net/optile/example/demo/summary/SummaryPresenter.java, example-demo/src/main/java/net/optile/example/demo/summary/SummaryView.java, example-demo/src/main/res/values/strings.xml, payment/src/main/java/net/optile/payment/ui/page/ChargePaymentPresenter.java, payment/src/main/java/net/optile/payment/ui/page/PaymentListPresenter.java
Remove all error dialogs for Interaction codes: ABORT and VERIFY.
=> PCX-913: Remove error dialogs from android-sdk

.gitignore, example-sdk/browserstack.json, example-shop/browserstack.json, example-shop/src/androidTest/java/net/optile/example/shop/AbstractTest.java, payment/src/main/AndroidManifest.xml
This PR adds additional test devices and versions for Browserstack.
=> PCX-1187: Fix redirect for Android 11

checkout/src/main/java/com/payoneer/checkout/form/Operation.java, checkout/src/main/java/com/payoneer/checkout/ui/PaymentUI.java, checkout/src/main/java/com/payoneer/checkout/ui/page/ChargePaymentActivity.java, checkout/src/main/java/com/payoneer/checkout/ui/page/ChargePaymentPresenter.java, example-shop/src/main/java/com/payoneer/checkout/exampleshop/summary/SummaryActivity.java
More details in the ticket [here](https://optile.atlassian.net/browse/PCX-2263)
=> PCX-2263: Remove required preset account object when charging preset account

example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/PresetAccountTests.java, example-checkout/src/main/java/com/payoneer/checkout/examplecheckout/ExampleCheckoutActivity.java
Added a missing unregister for the ResultIdlingResource.
=> PCX-2335/fix failed tests

example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/AbstractTest.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/CardPaymentTests.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/ExtraElementTests.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/PayPalRedirectTests.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/PresetAccountTests.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/RegistrationTests.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/SepaPaymentTests.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/Three3DS2Tests.java, example-checkout/src/main/java/com/payoneer/checkout/examplecheckout/ExampleCheckoutActivity.java, example-checkout/src/main/res/layout/activity_examplecheckout.xml, example-checkout/src/main/res/values/strings.xml, shared-test/src/main/java/com/payoneer/checkout/sharedtest/checkout/PaymentListHelper.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/checkout/TestDataProvider.java
=> Pcx 2335: support charge preset example checkout app

build.gradle, checkout/src/main/AndroidManifest.xml, example-checkout/src/main/AndroidManifest.xml, example-shop/src/main/AndroidManifest.xml
=> Pcx 2483 update versions

checkout/src/main/java/com/payoneer/checkout/ui/list/PresetCardViewHolder.java, checkout/src/main/java/com/payoneer/checkout/ui/service/PaymentSessionBuilder.java
=> PCX-2408: preset method one click

checkout/src/main/res/layout/view_icon.xml
=> PCX-2673: change app tint of delete color to gray

CHANGELOG.rst
Update CHANGELOG for release 0.81.0
=> PCX-2759: Update CHANGELOG

example-shop/src/main/java/com/payoneer/checkout/exampleshop/summary/SummaryViewModel.kt
Example Shop app fails to compile
See: https://optile.atlassian.net/browse/PCX-2927
=> PCX-2927: Remove context from ListConnection constructor

example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/ExampleCheckoutJavaActivityTest.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/ExampleCheckoutKotlinActivityTest.kt, example-shop/src/androidTest/java/com/payoneer/checkout/exampleshop/settings/SettingsActivityTest.kt, example-shop/src/main/java/com/payoneer/checkout/exampleshop/settings/SettingsActivity.kt, example-shop/src/main/res/values/strings.xml
This PR fixes a crash because of an empty input from the user as well as adding tests for the same to ensure this behaviour is maintained
=> PCX-3040: Fix crash and add tests

CHANGELOG.rst
Update changelog with the tickets that are released in the 0.91.0 release.
=> PCX-3196: Update changelog

README.md
Update the link in the readme to the correct documentation portal.
=> PCX-3197: Update readme

example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/PresetAccountTests.java
[PCX-3442](https://optile.atlassian.net/browse/PCX-3442)
Fix PresetAccount automated UI tests
=> PCX-3442: Remove registration of resultIdlingResource

README.md
[PCX-3437](https://optile.atlassian.net/browse/PCX-3437)
Link merchant to the correct documentation portal 
So that merchants find the most accurate information about the SDK
Update the read me docs with the correct link
N/A
=> PCX-3437: Update read me

example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/SepaPaymentTests.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/checkout/PaymentListHelper.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/view/PaymentMatchers.java
[PCX-3269](https://optile.atlassian.net/browse/PCX-3269)
Add helper methods to check Checkbox values
Check the SepaTests for an example, please remove this test later.
=> PCX-3269: Add Checkbox helper methods

CHANGELOG.rst
[PCX-3714](https://optile.atlassian.net/browse/PCX-3714)
Update CHANGELOG file with the latest bug and features that are included in the 0.93.0 release.
- Documentation update
=> PCX-3714: Update changelog

checkout/src/test/java/com/payoneer/checkout/ui/screen/payment/ProcessPaymentViewModelTest.java
[PCX-3840](https://optile.atlassian.net/browse/PCX-3840)
Add tests in Event class
To drive coverage and integrity of the SDK up
Test cases
=> PCX-3840: Add unit tests for com.payoneer.checkout.util.event

checkout/src/main/java/com/payoneer/checkout/util/ContentEvent.java, checkout/src/test/java/com/payoneer/checkout/ui/screen/list/PaymentListViewModelTest.java
[PCX-3839](https://optile.atlassian.net/browse/PCX-3839)
Add tests in ContentEvent class
To drive coverage and integrity of the SDK up
- Test cases
=> PCX-3839: Add unit tests for com.payoneer.checkout.util.content event

checkout/src/test/java/com/payoneer/checkout/util/GsonHelperTest.java
[PCX-3842](https://optile.atlassian.net/browse/PCX-3842)
Improve test coverage for GsonHelper class
To improve the stability of our code
Add more test cases
- Test cases
=> PCX-3842: Add tests for GsonHelper class
