optile/checkout-android

CHANGELOG.rst, README.rst
Update the changelog and readme file to support the new version 1.1.11 of the Android SDK.
=> Update Changelog and Readme files

payment/src/main/java/net/optile/payment/ui/page/PaymentPagePresenter.java
Handle the RETRY / EXPIRED_SESSION Interaction, this happens when a preset operation is executed on an expired list.
This will now result in a cancellation of the PaymentSession.
=> Handle RETRY / EXPIRED_SESSION Interaction

payment/src/sharedTest/res/raw/listtemplate.json
Remove registration id from the listtemplate.json.
This allows usage of other merchant profiles for automated tests without changing the listtemplate.json file.
=> Remove registration id

.ci/test.sh, payment/src/main/java/net/optile/payment/ui/list/NetworkCardViewHolder.java, payment/src/main/java/net/optile/payment/ui/model/AccountCard.java, payment/src/main/java/net/optile/payment/ui/model/NetworkCard.java, payment/src/main/java/net/optile/payment/ui/model/PaymentNetwork.java, payment/src/main/java/net/optile/payment/ui/model/PresetCard.java, payment/src/main/java/net/optile/payment/ui/model/SmartSwitch.java, payment/src/main/java/net/optile/payment/ui/service/PaymentSessionService.java
Remove smart switch logic from the NetworkCard and PaymentNetwork classes.
This makes it easier to re-use the PaymentNetwork class for GooglePay activation.
=> Pcx 313 smartswitch

example-basic/src/androidTest/java/net/optile/example/basic/PaymentListTests.java
Example basic app was referencing the root layout of the payment list activity with an outdated name.
=> Fix layout reference in the example-basic app

.ci/build.sh, .ci/release.sh, .ci/test.sh
gocd-scripts#105 changes the way we support gradle and this PR changes
.ci so that it works.
=> Change build scripts to work with new gradle support

example-sdk/src/androidTest/res/raw/listtemplate.json, example-shop/src/androidTest/res/raw/listtemplate.json, example-shop/src/main/res/values/strings.xml
The following has been changed:
- Change payment reference names
- remove notificationUrls from callback objects
- Change Shop Example amount to 69
- Change SDK Example amount to 13
=> PCX-1399: Update functional test list body

example-checkout/browserstack.gradle
**bug description**
ExampleCheckout app is using the ExampleShop browserstack profile
=> PCX-2275: Fix reference to browserstack example file

checkout/src/main/java/com/payoneer/checkout/ui/list/HeaderItem.java, checkout/src/main/java/com/payoneer/checkout/ui/list/ListAdapter.java, checkout/src/main/java/com/payoneer/checkout/ui/list/ListItem.java, checkout/src/main/java/com/payoneer/checkout/ui/list/PaymentCardItem.java, checkout/src/main/java/com/payoneer/checkout/ui/list/PaymentCardViewHolder.java, checkout/src/main/java/com/payoneer/checkout/ui/list/PaymentItemList.java, checkout/src/main/java/com/payoneer/checkout/ui/list/PaymentList.java, checkout/src/main/java/com/payoneer/checkout/ui/model/AccountCard.java, checkout/src/main/java/com/payoneer/checkout/ui/model/NetworkCard.java, checkout/src/main/java/com/payoneer/checkout/ui/model/PaymentCard.java, checkout/src/main/java/com/payoneer/checkout/ui/model/PaymentNetwork.java, checkout/src/main/java/com/payoneer/checkout/ui/model/PresetCard.java, checkout/src/main/java/com/payoneer/checkout/ui/service/PaymentSessionBuilder.java
When loading a LIST object with a PRESET account, the first thing viewable in the viewport is the UI card for the PRESET account, while the section title (“Previously selected”) and (potential) warning text are not visible.
=> PCX-2289: Scroll and open the correct selected payment card

.github/workflows/app_automate_test_examplecheckout.yml, .github/workflows/app_automate_test_exampleshop.yml, .github/workflows/app_live_upload_examplecheckout.yml, .github/workflows/app_live_upload_exampleshop.yml, .github/workflows/build.yml, .github/workflows/release.yml, checkout/publish.gradle, ci.gradle, example-checkout/browserstack.gradle, example-shop/browserstack.gradle
**AS** A developer
**I LIKE** to upload and test the Checkout SDK example apps from Github
**SO THAT** anybody can easily test and use the Android Checkout Examples
**Acceptance Criteria**
Create 4 manual Github Workflow actions
- Upload example-checkout app to Browserstack App live
- Upload example-shop app to Browserstack App live
- Run example-checkout UITests on Browserstack
- Run example-shop UITests on Browserstack
Both uploading and testing should be done on the active branch
=> PCX-2331: fix Browserstack workflows

example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/BaseTest.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/CancelPaymentTests.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/CheckoutJavaTests.java, example-checkout/src/main/java/com/payoneer/checkout/examplecheckout/ExampleCheckoutKotlinActivity.kt
Clicking the back button causes the app to crash in the Kotlin Example app.
**Acceptance Criteria**
Back button should be clickable
Automated UI tests should be written to test the back button in both the Example Checkout (Kotlin, Java) and Example Shop app.
**Details**
1. Platform/System/environment
Android Checkout SDK
2. Steps to reproduce
Open Checkout Example app and click the top/left back button
3. Current behaviour
NullPointerException is thrown
4. Expected behaviour
App should show that the user canceled the payment page
5. Test parameters how to reproduce
ANDROID_TESTING merchant on main integration
=> PCX-2567: Fix back navigation crash

.github/workflows/build.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml
All automated UI tests currently in the Android Checkout SDK should be run on Browserstack for all pull requests into develop branch. (Excluding draft PRs). Currently, only unit tests are run and this should be extended with automated UI tests.
See https://optile.atlassian.net/browse/PCX-2895
=> PCX-2895: Update workflow files for testing example apps for PRs

example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/BaseTest.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/RegistrationTests.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/checkout/TestDataProvider.java
Setting the recurrence flag to true will not allow deletion of accounts. The merchant MOBILE_TESTING on  pi-nightly has changed the settings for VISA, whereby the recurrence flag should now be “false”.
See https://optile.atlassian.net/browse/PCX-2974
=> PCX-2974: Remove recurrence and use mastercard

checkout/src/main/java/com/payoneer/checkout/Checkout.java, checkout/src/main/java/com/payoneer/checkout/CheckoutConfiguration.java, checkout/src/main/java/com/payoneer/checkout/network/BaseConnection.java, checkout/src/main/java/com/payoneer/checkout/network/ListConnection.java, checkout/src/main/java/com/payoneer/checkout/ui/service/PaymentSessionService.java, checkout/src/test/java/com/payoneer/checkout/network/ListConnectionTest.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/BaseTest.java, example-checkout/src/main/java/com/payoneer/checkout/examplecheckout/ExampleCheckoutJavaActivity.java, example-checkout/src/main/java/com/payoneer/checkout/examplecheckout/ExampleCheckoutKotlinActivity.kt, example-shop/src/androidTest/java/com/payoneer/checkout/exampleshop/AbstractTest.kt, example-shop/src/main/java/com/payoneer/checkout/exampleshop/checkout/CheckoutActivity.kt, example-shop/src/main/java/com/payoneer/checkout/exampleshop/settings/SettingsActivity.kt, example-shop/src/main/java/com/payoneer/checkout/exampleshop/summary/SummaryViewModel.kt, riskprovider/iovation/src/main/java/com/payoneer/checkout/risk/iovation/IovationRiskProvider.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/service/ListService.java
**WHAT**
[PCX-3040](https://optile.atlassian.net/browse/PCX-3040)
Changes the type of listurl from 'String' to 'URL'
**WHY**
So that the android and iOS sdks both have the same implementation to make it easier for the merchant.
More details in the ticket linked.
=> PCX-3040: Change list self url in android sdk to url object instead of string

build.gradle, checkout/build.gradle, example-checkout/build.gradle, example-shop/build.gradle, paymentservice/googlepay-braintree/build.gradle, riskprovider/iovation/build.gradle
Fix build scripts for GooglePay Braintree.
These build scripts upload the Googlepay Braintree module to Nexus and Packagecloud.
Without this update, GooglPay Braintree will not be published to Nexus and Packagecloud.
=> PCX-3279: Fix buildscripts for GooglePay Braintree

build.gradle, example-checkout/build.gradle, example-shop/build.gradle
[PCX-3277](https://optile.atlassian.net/browse/PCX-3277)
Updates library versions as well as enabling iovation for risk
To enable merchants to run the example apps with risk enable to see how it works and to use latest versions
This is done simply by updating the library versions an adding iovation dependencies in the gradle files
Tests for iovation have been added inside the risk provider directory, which has the iovation module.
=> PCX-3277: Update versions and enable iovation

build.gradle, checkout/src/main/java/com/payoneer/checkout/ui/screen/list/PaymentListViewModel.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/ExpiredCardTests.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/ExtraElementTests.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/checkout/PaymentListHelper.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/view/UiDeviceHelper.java
[PCX-3317](https://optile.atlassian.net/browse/PCX-3317)
When clicking an ExtraElement link which opens the custom chrome tab. After closing the custom tab, the app is reopened but the list is reloaded.
The Mobile SDK does not check if there is a previously loaded payment session. It always loads a new one when the PaymentList Screen is resumed.
Show the already loaded payment session, if previously loaded.
- Test cases
- Automated test has been added to validate that the correct payment card is opened when returning from the Chrome Custom tab.
=> PCX-3317: Disable reload when payment list is resumed

.github/workflows/pullrequest.yml, build.gradle, example-checkout/browserstack.gradle, example-checkout/build.gradle, example-shop/browserstack.gradle, example-shop/build.gradle
[PCX-3340](https://optile.atlassian.net/browse/PCX-3340)
Upload the Example Checkout app for feature branches to BrowserStack AppLive.
As an integration engineer / PO / Support person
I want to be able to access the latest version of our Android SDK Example Checkout app
so that I can compare feature branches to latest and/or present a stable SDK internally or externally
For each PR update into develop branch, the Example Checkout app are uploaded to AppLive.
=> PCX-3340: Upload PR Example Checkout app to AppLive

.github/workflows/build.yml
[PCX-2893](https://optile.atlassian.net/browse/PCX-2893)
For every merge of a PR into the develop branch, a version of the Example Checkout app should
be automatically uploaded to Browserstack AppLive.
As an integration engineer / PO / Support person
I want to be able to access the latest version of our Android SDK example app
so that I can compare feature branches to latest and/or present a stable SDK internally or externally
Upload the ExampleCheckout app to AppLive from the build.xml Github workflow.
=> PCX-2893: Upload example checkout app for develop branch builds

.github/workflows/build.yml, .github/workflows/release.yml, build.gradle
[PCX-2891](https://optile.atlassian.net/browse/PCX-2891)
Upload release version of the Example Checkout app for each release (merge to master)
As an integration engineer / PO / Support person
I want to be able to access the latest version of our Android SDK example app
so that I can compare feature branches to latest and/or present a stable SDK internally or externally
Upload example checkout app in the release.xml workflow file
=> PCX-2891: Upload ExampleCheckout app for each release to AppLive

example-checkout/build.gradle, example-shop/build.gradle, paymentservice/googlepay-braintree/README.md, paymentservice/googlepay-braintree/publish.gradle
[PCX-3367](https://optile.atlassian.net/browse/PCX-3367)
Disable upload of the GooglePay-Braintree PaymentService to PackageCloud.
GooglePay-Braintree PaymentService is under active development and thus it should not
be publicly released.
Disable upload to PackageCloud
=> PCX-3367: Disable GooglePay-Braintree upload to PackageCloud

example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/BaseTest.java, example-shop/src/androidTest/java/com/payoneer/checkout/exampleshop/AbstractTest.kt, shared-test/src/main/java/com/payoneer/checkout/sharedtest/checkout/PaymentDialogHelper.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/view/PaymentActions.java
[PCX-3442](https://optile.atlassian.net/browse/PCX-3442)
Fix an ignore on button click after Activity is resumed
To make sure tests are executed correctly
Instead of relying on a click at X,Y position, a force click is made when the View is enabled and displayed.
=> PCX-3442: Force click button using ViewAction

checkout/src/main/java/com/payoneer/checkout/account/DeleteAccount.java, checkout/src/main/java/com/payoneer/checkout/network/PaymentConnection.java
[PCX-3493](https://optile.atlassian.net/browse/PCX-3493)
Delete saved accounts do not work when they are registered with allowRecurrence
The last saved account with allowRecurrence is not allowed to delete 
Remove setting explicitly in the Android Checkout SDK that recurrence accounts must be deleted.
=> PCX-3493: Remove deregistration data

CHANGELOG.rst
[PCX-3375](https://optile.atlassian.net/browse/PCX-3375)
Update the CHANGELOG file with the tickets that will be added to the 0.92.0 release.
So that merchants can see which tickets are included in the 0.92.0 release.
- Documentation update
=> PCX-3375: Update Changelog

example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/BaseJavaTest.java, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/BaseKotlinTest.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/checkout/PaymentListHelper.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/checkout/ProcessPaymentHelper.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/view/PaymentActions.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/view/PaymentMatchers.java
[PCX-3605](https://optile.atlassian.net/browse/PCX-3605)
On rare occasions the getCurrentActivity returns the invalid activity although the Intent is launched.
Automated tests are randomly failing on Browserstack
Obtain the current activity using ViewMatchers instead of using the ActivityHelper class
=> PCX-3605: Use ViewMatcher to find the proper Activity

.github/workflows/build.yml, .github/workflows/release.yml
[PCX-3608](https://optile.atlassian.net/browse/PCX-3608)
Update NEXUS secrets in Android workflow files
Android Checkout SDK builds and releases are broken because of invalid NEXUS credentials used in Github.
Switch to new values for NEXUS.
=> PCX-3608 Updated NEXUS credentials.

checkout/src/main/java/com/payoneer/checkout/model/Checkbox.java, checkout/src/main/java/com/payoneer/checkout/ui/widget/CheckboxWidget.java, checkout/src/main/java/com/payoneer/checkout/ui/widget/ExtraElementWidget.java, checkout/src/main/java/com/payoneer/checkout/ui/widget/RegistrationWidget.java, checkout/src/main/res/layout/widget_checkbox.xml, checkout/src/main/res/values/strings.xml, example-checkout/src/androidTest/java/com/payoneer/checkout/examplecheckout/ExtraElementTests.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/checkout/PaymentListHelper.java, shared-test/src/main/java/com/payoneer/checkout/sharedtest/view/PaymentMatchers.java
[PCX-3503](https://optile.atlassian.net/browse/PCX-3503)
Validate the checkbox modes before submitting them back to OPG. Specifically, validate the ones with either `REQUIRED` or `REQUIRED_PRESELECTED` modes
We want to make sure that the users do not send requests if they have not fully agreed to the merchant's conditions
Add validation before the states are submitted to OPG
- Changes have been tested in UI tests where we check that the error messages are displayed upon clicking the pay button and upon toggling the `REQUIRED` or `REQUIRED_PRESELECTED` check boxes.
=> PCX-3503: Validate checkbox states
